hostname: localhost
port: 3001
file: default
test:
  hhh
mongodb: mongodb://localhost:27017/Movie

log4js:
  pm2: true
  disableClustering: true
  pm2InstanceVar: 'INSTANCE_ID'
  appenders:
    console:
      type: 'console'
  categories:
    default:
      appenders:
        - 'console'
      level: 'info'
#  tcp 微服务
tcp-micro-service:
    transport: 0
    options:
      host: "localhost"
      port: 63375

